### ISSUE TITLE
should not use arrow function

### ISSUE THREAD

**Issue by jseagull** [node-modules/utility#30]
`> const utils = require('utility');
~/utility/node_modules/utility/lib/json.js:54
  return new Promise((resolve, reject) => {
                                       ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/seagull/test/node/utility/node_modules/utility/lib/utility.js:12:6)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)`

**Comment by dead-horse** [comment]
fixed in 1.13.1
